[package]
name = "mango"
description = "The Mango programming language (UNDER CONSTRUCTION)"
# Note: until version 0.4.0, the crates.io 'mango' crate was what since 0.5.0 is 'mangolib'
version = "0.5.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]
homepage = "https://mangocode.org/"
license = "Apache-2.0"
edition = "2018"
publish = true
include = [
    "src/**/*",
    "Cargo.toml"
]

[[bin]]
name = "mango"
path = "src/main.rs"

[dependencies]
mangolib = { path = "../compiler" }
#mangolib = "0.5.0"
structopt = { version = "0.3.21", features = [ "paw" ] }
paw = "1.0.0"
#lazy_static = "^1.4.0"

# Usage based on https://github.com/gnzlbg/jemallocator
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]

[profile.release]
lto = 'thin'
opt-level = 'z'

[profile.dev.package."*"]
opt-level = 3
debug = false
