
[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"

[bans]
multiple-versions = "deny"
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
]

exceptions = [
    { allow = ["Zlib"], name = "tinyvec" },
]

