
# Check that the code compiles. Also checks tests and style, but non-blocking.

name: 'Create a release'

on:
  workflow_dispatch:

jobs:
  github:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build for CI
        run: bash ci/pipeline/make/debug.sh
      - name: Optimized image
        run: bash ci/pipeline/release/dist_image.sh
      - name: Binary (linux)
        run: bash ci/pipeline/release/dist_exe.sh
      - name: Executable info
        run: bash ci/pipeline/release/exe_info.sh
      - name: Static files
        run: bash ci/pipeline/release/static_files.sh
      - name: Cli api help
        run: bash ci/pipeline/release/api_help.sh
      - name: Documentation
        run: bash ci/pipeline/make/docs.sh
      - uses: actions/upload-artifact@v2
        with:
          name: mango-artifact
          path: ./artifact/mango-*/*
          if-no-files-found: error
      - name: Package
        run: bash ci/pipeline/release/package.sh
      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          dockerfile: ci/image/executable.Dockerfile
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango
          tags: latest
#      - name: Upload the artifacts
#        uses: skx/github-action-publish-binaries@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: './artifact/mango-*.zip'
