
# Check that the code compiles. Also checks tests and style, but non-blocking.

name: 'Create a release'

on:
  push:  #TODO @mark: TEMPORARY! REMOVE THIS!
  workflow_dispatch:

jobs:
  github:
    name: Compile and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build for CI
        run: ci/pipeline/make/debug.sh
      - name: Optimized image
        run: ci/pipeline/release/dist_image.sh
      - name: Binary (linux)
        run: ci/pipeline/release/dist_exe.sh
      - name: Executable info
        run: ci/pipeline/release/exe_info.sh
      - name: Static files
        run: ci/pipeline/release/static_files.sh
      - name: Documentation
        run: ci/pipeline/make/docs.sh
      - name: Push to DockerHub
        uses: docker/build-push-action@v1.0
        with:
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango
          tags: latest
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'example-*'
