
# This builds a base image containing the pre-compiled dependencies.
# It is automatically built every day so that subsequent builds are fast.

name: 'Daily Mango base image'

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

#TODO @mark: should only build if it does not exist

jobs:
  push_to_registry:
    name: Daily base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stop if no changes
        continue-on-error: true
        run: |
          if [ "$(expr $(date +'%s') - $(git show -s --format='%ct' "$GITHUB_SHA"))" -lt 90000 ]
          then
              echo "::set-env name=LATEST_IS_FRESH::true"
          else
              printf "last commit $GITHUB_SHA was too old ($(git show -s --format='%ci' master)); image already pushed"
          fi
      - name: Push to DockerHub (stable)
        if: ${{ env.LATEST_IS_FRESH }}
        uses: docker/build-push-action@v1
        with:
          dockerfile: ci/image/base.Dockerfile
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango_daily_base
          tags: stable
      - name: Push to DockerHub (nightly)
        if: ${{ env.LATEST_IS_FRESH }}
        uses: docker/build-push-action@v1
        with:
          dockerfile: ci/image/base_nightly.Dockerfile
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango_daily_base
          tags: nightly
