
# This builds a base image containing the pre-compiled dependencies.
# It is automatically built every day so that subsequent builds are fast.

name: 'Daily Mango base image'

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

#TODO @mark: should only build if it does not exist

jobs:
  push_to_registry:
    name: Daily stable image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to DockerHub (stable)
        uses: docker/build-push-action@v1
        dockerfile: ci/image/base.Dockerfile
        with:
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango_daily_base
          tags: stable
      - name: Push to DockerHub (nightly)
        uses: docker/build-push-action@v1
        dockerfile: ci/image/base_nightly.Dockerfile
        with:
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango_daily_base
          tags: nigthly
