
# This builds a base image containing the pre-compiled dependencies.
# It is automatically built every day so that subsequent builds are fast.

name: 'Daily Mango base image'

on:
  schedule:
    - cron: '0 3 * * 0'
  push:  #TODO @mark: TEMPORARY! REMOVE THIS!
  workflow_dispatch:

#TODO @mark: should only build if it does not exist

jobs:
  push_to_registry:
    name: Daily stable image
    # IF the last commit was less than 25 hours ago (if older, image is up-to-date).
    if: sh -c "[ "$(expr $(date +'%s') - $(git show -s --format='%ct' $GITHUB_SHA))" -lt 90000 ]"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to DockerHub (stable)
        uses: docker/build-push-action@v1
        with:
          dockerfile: ci/image/base.Dockerfile
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango_daily_base
          tags: stable
      - name: Push to DockerHub (nightly)
        uses: docker/build-push-action@v1
        with:
          dockerfile: ci/image/base_nightly.Dockerfile
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango_daily_base
          tags: nigthly
