
# Build a Docker image and push it to DockerHub.
# Based on https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images

name: 'Publish Mango CLI Docker'

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango
#         tag_with_ref: true
