
name: 'Publish Docker image for Mango CLI using simple image'

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  checks:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          dockerfile: ci/simple.Dockerfile
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: mangocode/mango
          tags: |
            latest
            nightly-${{ env.CURRENT_DATE }}
