
name: 'Publish Docker image for Mango CLI using simple image'

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  checks:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mangocode
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: latest,nightly-${{ steps.date.outputs.date }}

